### PR TITLE
Improve cluster selection

### PR DESCRIPTION
**Pull request by jackcmay**
Improve cluster selection
- use npm scripts to choose the cluster (including local)
- clean the configuration store when changing cluster to prevent the user from trying to talk to a non-existent program

### CODE REVIEW

**Comment by jstarry** [comment]
lgtm

**Comment by jackcmay** [comment]
wdyt about also applying this to the other examples?

**Comment by jstarry** [comment]
Not opposed. I think using `.env` files is a bit more of a standard approach to this problem

**Comment by jackcmay** [comment]
Cool, learn something new every day.  Would still like the user to run an npm script so that other cleanup stuff can run when switching clusters.  @jstarry were you thinking that the npm script would swap in the appropriate `.env` file?

**Comment by jstarry** [comment]
Yup!

**Pull request merged**
