### PR TITLE
Update cargo dependencies to latest

### PR DESCRIPTION
**Pull request by Tirka**
Consistent usage of `borsh` across different crates

### CODE REVIEW

**Comment by jstarry** [comment]
Thanks @Tirka, do you mind bumping the `solana-program` version while you're at it?

**Comment by Tirka** [comment]
> 
> 
> Thanks @Tirka, do you mind bumping the `solana-program` version while you're at it?

Should I also try to do `cargo update` after that to update `cargo.lock`?

**Comment by jstarry** [comment]
Sounds good to me!

**Comment by Tirka** [comment]
Done. Tests are green. I don't see any issues

**Comment by jstarry** [comment]
@Tirka can you take a look at the CI failure?

**Comment by Tirka** [comment]
I found these lines at logs:
```
BPF SDK: /home/runner/.local/share/solana/install/releases/1.6.6/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: rustup toolchain link bpf /home/runner/.local/share/solana/install/releases/1.6.6/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Updating crates.io index
error: failed to download `solana-frozen-abi v1.7.9`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-frozen-abi-1.7.9/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

Any ideas how to fix it?

**Comment by jstarry** [comment]
The issue was that the Solana cli tools needed to be updated to use a higher version of rust which supports the new cargo resolver

**Comment by jstarry** [comment]
I copied your updates over here and merged, thanks! https://github.com/solana-labs/example-helloworld/pull/269

**Pull request closed without merging**
