### PR TITLE
Change solana config localhost to 127.0.0.1

### PR DESCRIPTION
**Pull request by CalebEverett**

### CODE REVIEW

**Comment by jstarry** [comment]
Thanks @CalebEverett, seems like we could fix this here as well if you're up for it: https://github.com/solana-labs/solana/blob/9c5d82557a965cf23831a3fb2e3b8986d379ce04/clap-utils/src/input_validators.rs#L219

**Comment by CalebEverett** [comment]
sure, that looks better

**Comment by jstarry** [comment]
Your change here is fine for now though, merging. Thanks!

**Comment by CalebEverett** [comment]
@jstarry There are a good number of other instances throughout the solana repo - do you want to take a quick look and let me know if we should change any others in addition to clap-utils?

```
git grep -n http://localhost
```

**Comment by jstarry** [comment]
> @jstarry There are a good number of other instances throughout the solana repo - do you want to take a quick look and let me know if we should change any others in addition to clap-utils?

Good question, I think we can just update anything affecting the cli so that'd be: `./clap-utils`, `./cli-config`, and `./cli`. Thanks!

**Comment by CalebEverett** [comment]
There was just one additional instance in an example in `./cli-config` and one in `./cli`. Let me know if you want me to submit.

https://github.com/CalebEverett/solana/commit/77d2298d1e199c8a503faa0811257c354ffa5f19

**Pull request merged**
